### ISSUE TITLE
可否添加后端支持free-chatgpt？

### ISSUE THREAD

**Issue by ClassmateLin** [zhpd/chatgpt-plus#23]
这个API是免费的, 无需token和key就可以使用了。还不需要使用代理。
[free-chatgpt](https://github.com/ClassmateLin/free-chatgpt)

**Comment by zhpd** [comment]
> 这个API是免费的, 无需token和key就可以使用了。还不需要使用代理。 [free-chatgpt](https://github.com/ClassmateLin/free-chatgpt)

如果接口返回数据是跟chatgpt一致的，那可以使用的，替换成这个后端接口就行
