### ISSUE TITLE
vercel部署遇到问题

### ISSUE THREAD

**Issue by vlinglandy** [zhpd/chatgpt-plus#8]
作者你好，我本地是能正常使用的，目前我是开了两个仓库，分别用vercel部署前端和后端，接口是通的，但是报以下错误，这个怎么解决哇
Cannot find package 'chatgpt' imported from /var/task/service/src/modules/chatgpt/chatgpt.service.js
![image](https://user-images.githubusercontent.com/66253966/231219389-a32ffbde-37ed-4319-b6d0-66330caf06f3.png)

**Comment by zhpd** [comment]
后端使用docker或者打包部署运行，不建议部署在vercel，免费版的vercel有运行时长限制，会断开流式请求

**Comment by zhpd** [comment]
ChatGPT错误429:{“错误”:[和计费详细信息。“类型”
“消息”:“您超出了当前的配额，请检查您的计划
“不足 配额”，
“参数”: null，
“代码”: null]

**Comment by zhpd** [comment]
检查下ChatGPT账户，配额不足。
ChatGPT错误429:{“错误”:[和计费详细信息。“类型”
“消息”:“您超出了当前的配额，请检查您的计划
“不足 配额”，
“参数”: null，
“代码”: null]

**Comment by zhpd** [comment]
> <img alt="image" width="674" src="https://user-images.githubusercontent.com/36947908/231501349-c4d3cec1-a1cf-4fab-a40d-ae1ddb140126.png">
> 
> 大佬好 , 我现在部署本地卡到这了 请问这是什么原因

检查下ChatGPT账户，配额不足。
ChatGPT错误429:{“错误”:[和计费详细信息。“类型”
“消息”:“您超出了当前的配额，请检查您的计划
“不足 配额”，
“参数”: null，
“代码”: null]

**Comment by vlinglandy** [comment]
太棒了，我部署成功了，访问的很快！

**Comment by pangao66** [comment]
@vlinglandy  你前后端都用vercel部署的吗？  能实现流式返回 打字机效果吗？
